/*

 BGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 37 x 37
   Tile set      : tree2BaseTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BGMap_h_INCLUDE
#define __BGMap_h_INCLUDE

#define BGMapWidth 37
#define BGMapHeight 37
#define BGMapBank 1

#define BGMap BGMapPLN0
extern const void __bank_BGMapPLN0;
extern const unsigned char BGMapPLN0[];

#endif

/* End of BGMAP.H */
