/*

 FGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 50 x 50
   Tile set      : FGTilesOffset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 68
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __FGMap_h_INCLUDE
#define __FGMap_h_INCLUDE

#define FGMapWidth 50
#define FGMapHeight 50
#define FGMapBank 1

#define FGMap FGMapPLN0
extern const void __bank_FGMapPLN0;
extern const unsigned char FGMapPLN0[];

#endif

/* End of FGMAP.H */
