/*

 FGMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 32 x 32
   Tile set      : C:\GBParallax\Graphics\FGTiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 77
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __FGMap_h_INCLUDE
#define __FGMap_h_INCLUDE

#define FGMapWidth 32
#define FGMapHeight 32
#define FGMapBank 1

#define FGMap FGMapPLN0
extern const void __bank_FGMapPLN0;
extern const unsigned char FGMapPLN0[];
extern const void __bank_FGMapPLN01;
extern const unsigned char FGMapPLN1[];

#endif

/* End of FGMAP.H */
