/*

 FGTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __FGTiles_h_INCLUDE
#define __FGTiles_h_INCLUDE

/* Bank of tiles. */
#define ForegroundTilesBank 1
/* Start of tile array. */
extern const void __bank_ForegroundTiles;
extern const unsigned char ForegroundTiles[];

#endif

/* End of FGTILES.H */
