/*

 TREEBASETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 521

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __TreeBaseTiles_h_INCLUDE
#define __TreeBaseTiles_h_INCLUDE

/* Bank of tiles. */
#define TreeBaseTilesBank 1

/* Super Gameboy palette 0 */
#define TreeBaseTilesSGBPal0c0 6076
#define TreeBaseTilesSGBPal0c1 8935
#define TreeBaseTilesSGBPal0c2 6596
#define TreeBaseTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TreeBaseTilesSGBPal1c0 6076
#define TreeBaseTilesSGBPal1c1 8935
#define TreeBaseTilesSGBPal1c2 6596
#define TreeBaseTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TreeBaseTilesSGBPal2c0 6076
#define TreeBaseTilesSGBPal2c1 8935
#define TreeBaseTilesSGBPal2c2 6596
#define TreeBaseTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TreeBaseTilesSGBPal3c0 6076
#define TreeBaseTilesSGBPal3c1 8935
#define TreeBaseTilesSGBPal3c2 6596
#define TreeBaseTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TreeBaseTilesCGBPal0c0 18208
#define TreeBaseTilesCGBPal0c1 21088
#define TreeBaseTilesCGBPal0c2 16609
#define TreeBaseTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TreeBaseTilesCGBPal1c0 30701
#define TreeBaseTilesCGBPal1c1 19328
#define TreeBaseTilesCGBPal1c2 12705
#define TreeBaseTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define TreeBaseTilesCGBPal2c0 6076
#define TreeBaseTilesCGBPal2c1 8935
#define TreeBaseTilesCGBPal2c2 6596
#define TreeBaseTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TreeBaseTilesCGBPal3c0 6076
#define TreeBaseTilesCGBPal3c1 8935
#define TreeBaseTilesCGBPal3c2 6596
#define TreeBaseTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TreeBaseTilesCGBPal4c0 6076
#define TreeBaseTilesCGBPal4c1 8935
#define TreeBaseTilesCGBPal4c2 6596
#define TreeBaseTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TreeBaseTilesCGBPal5c0 6076
#define TreeBaseTilesCGBPal5c1 8935
#define TreeBaseTilesCGBPal5c2 6596
#define TreeBaseTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TreeBaseTilesCGBPal6c0 6076
#define TreeBaseTilesCGBPal6c1 8935
#define TreeBaseTilesCGBPal6c2 6596
#define TreeBaseTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TreeBaseTilesCGBPal7c0 6076
#define TreeBaseTilesCGBPal7c1 8935
#define TreeBaseTilesCGBPal7c2 6596
#define TreeBaseTilesCGBPal7c3 5344
/* Start of tile array. */
extern const void __bank_TreeBaseTiles;
extern const unsigned char TreeBaseTiles[];

#endif

/* End of TREEBASETILES.H */
